### ISSUE TITLE
New release needed

### ISSUE THREAD

**Issue by gpoulin-hopper** [google-github-actions/get-secretmanager-secrets#129]
### TL;DR
The latest release v0.2.2 is many months old and doesn't support WIF. We would like to have a new release so we can pin the version we use instead of using `@main`

**Comment by bharathkkb** [comment]
Thanks for the report @gpoulin-hopper. New release has been cut https://github.com/google-github-actions/get-secretmanager-secrets/releases/tag/v0.3.0
