### ISSUE TITLE
Is there a way to output the secret into a json file?

### ISSUE THREAD

**Issue by chinesehemp** [google-github-actions/get-secretmanager-secrets#240]
### TL;DR

Is there a way to output the secret into a JSON file to the project root like gcloud beta cli?

`gcloud beta secrets versions access --secret=default latest > config.json`

### Detailed design

I have a firebase project where my secrets are stored as a JSON file in the project root directory.

I would like to use https://github.com/FirebaseExtended/action-hosting-deploy to manage my deployment to firebase hosting and inject the secret as a JSON file into the root during the build process.

**Comment by sethvargo** [comment]
Hi @chinesehemp 

You could do exactly what you typed above using the setup-gcloud wrapper. Alternatively, you could use this action to download the secrets and then use another action to write to a file - there's quite a few options in the GitHub Actions Marketplace.

**Comment by chinesehemp** [comment]
Thank you!
