### ISSUE TITLE
New method to fetch the latest enabled version 

### ISSUE THREAD

**Issue by shiralwz** [google-github-actions/get-secretmanager-secrets#268]
### TL;DR

At present, we employ the most recent version of the system, irrespective of its enable status. Consequently, if version 2 is disabled and version 1 is enabled, it would result in an error.

**Comment by shiralwz** [comment]
Sorry for the confusion, I've updated the title from "active" to "enable"

**Comment by sethvargo** [comment]
I see. This issue tracker is for questions related to the GitHub Action for interacting with Google Secret Manager. For general Secret Manager feedback and questions, please see https://cloud.google.com/support. Thanks!

**Comment by chawes13** [comment]
@sethvargo I'm running into this scenario as well and to my knowledge, it isn't related to general Secret Manager feedback.

Scenario:
| version | status |
| --- | --- |
| 4 | Destroyed |
| 3 | Enabled |
| 2 | Disabled |
| 1 | Disabled |

With this setup, I receive the following error: 
```
google-github-actions/get-secretmanager-secrets failed with: failed to access secret "<path>/versions/latest": (400) {
  "error": {
    "code": 400,
    "message": "Secret Version [<path>/versions/4] is in DESTROYED state.",
    "status": "FAILED_PRECONDITION"
  }
}
```
I have the same request as @lucia-w - pull the latest _enabled_ version, not the latest version. If one doesn't exist, then I'd expect the job to fail.
