### ISSUE TITLE
Do we have options to Tokenize the secrets in json file by extracting the actual secret values form gcp secret manager

### ISSUE THREAD

**Issue by kondurure** [google-github-actions/get-secretmanager-secrets#290]
Do we have options to Tokenization / Replacing secert values the secrets in json file by extracting from actual secret values form gcp secret manager.

ex:
Json file content:

```json
[
    {
        "entry": [
            {
                "name": "username",
                "value": "abc"
            },
            {
                "name": "password",
                "value": "projects/Project-ID/secrets/password-test"
            }
        ],
        "name": "test-secret"
    }
]
```

here i created secret "test" in secret manager, i want to replace json file value with actual value of password-test from secret manager.

here i mentioned only one secret, like this we have hundreds of secrets json file.

**Comment by sethvargo** [comment]
Hi @kondurure - no, that would be well outside the scope of what this GitHub Action does. You could use this GitHub Action to fetch the secret and then use another tool such as envstub, sed, or jq to replace the value in the JSON.
